language: R
sudo: true

r:
  - release
  - devel
  
dist: trusty


after_success:
  - Rscript -e 'covr::codecov()'
  
before_install:
  - sudo apt-get install --yes libproj-dev
  - Rscript -e 'update.packages(ask = FALSE)'